//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.11.19 at 11:20:40 AM CST 
//


package com.origingame.server.dao.jaxb;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.origingame.server.dao.jaxb package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.origingame.server.dao.jaxb
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link com.origingame.server.dao.jaxb.ServerPersistence }
     * 
     */
    public ServerPersistence createServerPersistence() {
        return new ServerPersistence();
    }

    /**
     * Create an instance of {@link com.origingame.server.dao.jaxb.ServerPersistence.PlayerDbList }
     * 
     */
    public ServerPersistence.PlayerDbList createServerPersistencePlayerDbList() {
        return new ServerPersistence.PlayerDbList();
    }

    /**
     * Create an instance of {@link com.origingame.server.dao.jaxb.ServerPersistence.DbList }
     * 
     */
    public ServerPersistence.DbList createServerPersistenceDbList() {
        return new ServerPersistence.DbList();
    }

    /**
     * Create an instance of {@link com.origingame.server.dao.jaxb.ServerPersistence.CenterDb }
     * 
     */
    public ServerPersistence.CenterDb createServerPersistenceCenterDb() {
        return new ServerPersistence.CenterDb();
    }

    /**
     * Create an instance of {@link com.origingame.server.dao.jaxb.ServerPersistence.PlayerDbList.PlayerDb }
     * 
     */
    public ServerPersistence.PlayerDbList.PlayerDb createServerPersistencePlayerDbListPlayerDb() {
        return new ServerPersistence.PlayerDbList.PlayerDb();
    }

    /**
     * Create an instance of {@link com.origingame.server.dao.jaxb.ServerPersistence.DbList.Db }
     * 
     */
    public ServerPersistence.DbList.Db createServerPersistenceDbListDb() {
        return new ServerPersistence.DbList.Db();
    }

}
