// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: model/player_model.proto

package com.origingame.model;

public final class PlayerModelProtos {
  private PlayerModelProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface PlayerModelOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.origingame.model.PlayerModel)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional int32 id = 1;</code>
     */
    boolean hasId();
    /**
     * <code>optional int32 id = 1;</code>
     */
    int getId();

    /**
     * <code>optional .com.origingame.model.PlayerProperty property = 2;</code>
     */
    boolean hasProperty();
    /**
     * <code>optional .com.origingame.model.PlayerProperty property = 2;</code>
     */
    com.origingame.model.PlayerPropertyProtos.PlayerProperty getProperty();
    /**
     * <code>optional .com.origingame.model.PlayerProperty property = 2;</code>
     */
    com.origingame.model.PlayerPropertyProtos.PlayerPropertyOrBuilder getPropertyOrBuilder();

    /**
     * <code>repeated .com.origingame.model.PlayerItem items = 21;</code>
     */
    java.util.List<com.origingame.model.PlayerItemProtos.PlayerItem> 
        getItemsList();
    /**
     * <code>repeated .com.origingame.model.PlayerItem items = 21;</code>
     */
    com.origingame.model.PlayerItemProtos.PlayerItem getItems(int index);
    /**
     * <code>repeated .com.origingame.model.PlayerItem items = 21;</code>
     */
    int getItemsCount();
    /**
     * <code>repeated .com.origingame.model.PlayerItem items = 21;</code>
     */
    java.util.List<? extends com.origingame.model.PlayerItemProtos.PlayerItemOrBuilder> 
        getItemsOrBuilderList();
    /**
     * <code>repeated .com.origingame.model.PlayerItem items = 21;</code>
     */
    com.origingame.model.PlayerItemProtos.PlayerItemOrBuilder getItemsOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code com.origingame.model.PlayerModel}
   */
  public static final class PlayerModel extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:com.origingame.model.PlayerModel)
      PlayerModelOrBuilder {
    // Use PlayerModel.newBuilder() to construct.
    private PlayerModel(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private PlayerModel(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final PlayerModel defaultInstance;
    public static PlayerModel getDefaultInstance() {
      return defaultInstance;
    }

    public PlayerModel getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private PlayerModel(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              id_ = input.readInt32();
              break;
            }
            case 18: {
              com.origingame.model.PlayerPropertyProtos.PlayerProperty.Builder subBuilder = null;
              if (((bitField0_ & 0x00000002) == 0x00000002)) {
                subBuilder = property_.toBuilder();
              }
              property_ = input.readMessage(com.origingame.model.PlayerPropertyProtos.PlayerProperty.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(property_);
                property_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000002;
              break;
            }
            case 170: {
              if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
                items_ = new java.util.ArrayList<com.origingame.model.PlayerItemProtos.PlayerItem>();
                mutable_bitField0_ |= 0x00000004;
              }
              items_.add(input.readMessage(com.origingame.model.PlayerItemProtos.PlayerItem.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
          items_ = java.util.Collections.unmodifiableList(items_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.origingame.model.PlayerModelProtos.internal_static_com_origingame_model_PlayerModel_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.origingame.model.PlayerModelProtos.internal_static_com_origingame_model_PlayerModel_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.origingame.model.PlayerModelProtos.PlayerModel.class, com.origingame.model.PlayerModelProtos.PlayerModel.Builder.class);
    }

    public static com.google.protobuf.Parser<PlayerModel> PARSER =
        new com.google.protobuf.AbstractParser<PlayerModel>() {
      public PlayerModel parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new PlayerModel(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<PlayerModel> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int ID_FIELD_NUMBER = 1;
    private int id_;
    /**
     * <code>optional int32 id = 1;</code>
     */
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional int32 id = 1;</code>
     */
    public int getId() {
      return id_;
    }

    public static final int PROPERTY_FIELD_NUMBER = 2;
    private com.origingame.model.PlayerPropertyProtos.PlayerProperty property_;
    /**
     * <code>optional .com.origingame.model.PlayerProperty property = 2;</code>
     */
    public boolean hasProperty() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional .com.origingame.model.PlayerProperty property = 2;</code>
     */
    public com.origingame.model.PlayerPropertyProtos.PlayerProperty getProperty() {
      return property_;
    }
    /**
     * <code>optional .com.origingame.model.PlayerProperty property = 2;</code>
     */
    public com.origingame.model.PlayerPropertyProtos.PlayerPropertyOrBuilder getPropertyOrBuilder() {
      return property_;
    }

    public static final int ITEMS_FIELD_NUMBER = 21;
    private java.util.List<com.origingame.model.PlayerItemProtos.PlayerItem> items_;
    /**
     * <code>repeated .com.origingame.model.PlayerItem items = 21;</code>
     */
    public java.util.List<com.origingame.model.PlayerItemProtos.PlayerItem> getItemsList() {
      return items_;
    }
    /**
     * <code>repeated .com.origingame.model.PlayerItem items = 21;</code>
     */
    public java.util.List<? extends com.origingame.model.PlayerItemProtos.PlayerItemOrBuilder> 
        getItemsOrBuilderList() {
      return items_;
    }
    /**
     * <code>repeated .com.origingame.model.PlayerItem items = 21;</code>
     */
    public int getItemsCount() {
      return items_.size();
    }
    /**
     * <code>repeated .com.origingame.model.PlayerItem items = 21;</code>
     */
    public com.origingame.model.PlayerItemProtos.PlayerItem getItems(int index) {
      return items_.get(index);
    }
    /**
     * <code>repeated .com.origingame.model.PlayerItem items = 21;</code>
     */
    public com.origingame.model.PlayerItemProtos.PlayerItemOrBuilder getItemsOrBuilder(
        int index) {
      return items_.get(index);
    }

    private void initFields() {
      id_ = 0;
      property_ = com.origingame.model.PlayerPropertyProtos.PlayerProperty.getDefaultInstance();
      items_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeMessage(2, property_);
      }
      for (int i = 0; i < items_.size(); i++) {
        output.writeMessage(21, items_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, property_);
      }
      for (int i = 0; i < items_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(21, items_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.origingame.model.PlayerModelProtos.PlayerModel parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.origingame.model.PlayerModelProtos.PlayerModel parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.origingame.model.PlayerModelProtos.PlayerModel parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.origingame.model.PlayerModelProtos.PlayerModel parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.origingame.model.PlayerModelProtos.PlayerModel parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.origingame.model.PlayerModelProtos.PlayerModel parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.origingame.model.PlayerModelProtos.PlayerModel parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.origingame.model.PlayerModelProtos.PlayerModel parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.origingame.model.PlayerModelProtos.PlayerModel parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.origingame.model.PlayerModelProtos.PlayerModel parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.origingame.model.PlayerModelProtos.PlayerModel prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.origingame.model.PlayerModel}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.origingame.model.PlayerModel)
        com.origingame.model.PlayerModelProtos.PlayerModelOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.origingame.model.PlayerModelProtos.internal_static_com_origingame_model_PlayerModel_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.origingame.model.PlayerModelProtos.internal_static_com_origingame_model_PlayerModel_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.origingame.model.PlayerModelProtos.PlayerModel.class, com.origingame.model.PlayerModelProtos.PlayerModel.Builder.class);
      }

      // Construct using com.origingame.model.PlayerModelProtos.PlayerModel.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getPropertyFieldBuilder();
          getItemsFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        id_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        if (propertyBuilder_ == null) {
          property_ = com.origingame.model.PlayerPropertyProtos.PlayerProperty.getDefaultInstance();
        } else {
          propertyBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        if (itemsBuilder_ == null) {
          items_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
        } else {
          itemsBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.origingame.model.PlayerModelProtos.internal_static_com_origingame_model_PlayerModel_descriptor;
      }

      public com.origingame.model.PlayerModelProtos.PlayerModel getDefaultInstanceForType() {
        return com.origingame.model.PlayerModelProtos.PlayerModel.getDefaultInstance();
      }

      public com.origingame.model.PlayerModelProtos.PlayerModel build() {
        com.origingame.model.PlayerModelProtos.PlayerModel result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.origingame.model.PlayerModelProtos.PlayerModel buildPartial() {
        com.origingame.model.PlayerModelProtos.PlayerModel result = new com.origingame.model.PlayerModelProtos.PlayerModel(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.id_ = id_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        if (propertyBuilder_ == null) {
          result.property_ = property_;
        } else {
          result.property_ = propertyBuilder_.build();
        }
        if (itemsBuilder_ == null) {
          if (((bitField0_ & 0x00000004) == 0x00000004)) {
            items_ = java.util.Collections.unmodifiableList(items_);
            bitField0_ = (bitField0_ & ~0x00000004);
          }
          result.items_ = items_;
        } else {
          result.items_ = itemsBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.origingame.model.PlayerModelProtos.PlayerModel) {
          return mergeFrom((com.origingame.model.PlayerModelProtos.PlayerModel)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.origingame.model.PlayerModelProtos.PlayerModel other) {
        if (other == com.origingame.model.PlayerModelProtos.PlayerModel.getDefaultInstance()) return this;
        if (other.hasId()) {
          setId(other.getId());
        }
        if (other.hasProperty()) {
          mergeProperty(other.getProperty());
        }
        if (itemsBuilder_ == null) {
          if (!other.items_.isEmpty()) {
            if (items_.isEmpty()) {
              items_ = other.items_;
              bitField0_ = (bitField0_ & ~0x00000004);
            } else {
              ensureItemsIsMutable();
              items_.addAll(other.items_);
            }
            onChanged();
          }
        } else {
          if (!other.items_.isEmpty()) {
            if (itemsBuilder_.isEmpty()) {
              itemsBuilder_.dispose();
              itemsBuilder_ = null;
              items_ = other.items_;
              bitField0_ = (bitField0_ & ~0x00000004);
              itemsBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getItemsFieldBuilder() : null;
            } else {
              itemsBuilder_.addAllMessages(other.items_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.origingame.model.PlayerModelProtos.PlayerModel parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.origingame.model.PlayerModelProtos.PlayerModel) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int id_ ;
      /**
       * <code>optional int32 id = 1;</code>
       */
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional int32 id = 1;</code>
       */
      public int getId() {
        return id_;
      }
      /**
       * <code>optional int32 id = 1;</code>
       */
      public Builder setId(int value) {
        bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 id = 1;</code>
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0;
        onChanged();
        return this;
      }

      private com.origingame.model.PlayerPropertyProtos.PlayerProperty property_ = com.origingame.model.PlayerPropertyProtos.PlayerProperty.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          com.origingame.model.PlayerPropertyProtos.PlayerProperty, com.origingame.model.PlayerPropertyProtos.PlayerProperty.Builder, com.origingame.model.PlayerPropertyProtos.PlayerPropertyOrBuilder> propertyBuilder_;
      /**
       * <code>optional .com.origingame.model.PlayerProperty property = 2;</code>
       */
      public boolean hasProperty() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional .com.origingame.model.PlayerProperty property = 2;</code>
       */
      public com.origingame.model.PlayerPropertyProtos.PlayerProperty getProperty() {
        if (propertyBuilder_ == null) {
          return property_;
        } else {
          return propertyBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .com.origingame.model.PlayerProperty property = 2;</code>
       */
      public Builder setProperty(com.origingame.model.PlayerPropertyProtos.PlayerProperty value) {
        if (propertyBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          property_ = value;
          onChanged();
        } else {
          propertyBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .com.origingame.model.PlayerProperty property = 2;</code>
       */
      public Builder setProperty(
          com.origingame.model.PlayerPropertyProtos.PlayerProperty.Builder builderForValue) {
        if (propertyBuilder_ == null) {
          property_ = builderForValue.build();
          onChanged();
        } else {
          propertyBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .com.origingame.model.PlayerProperty property = 2;</code>
       */
      public Builder mergeProperty(com.origingame.model.PlayerPropertyProtos.PlayerProperty value) {
        if (propertyBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002) &&
              property_ != com.origingame.model.PlayerPropertyProtos.PlayerProperty.getDefaultInstance()) {
            property_ =
              com.origingame.model.PlayerPropertyProtos.PlayerProperty.newBuilder(property_).mergeFrom(value).buildPartial();
          } else {
            property_ = value;
          }
          onChanged();
        } else {
          propertyBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .com.origingame.model.PlayerProperty property = 2;</code>
       */
      public Builder clearProperty() {
        if (propertyBuilder_ == null) {
          property_ = com.origingame.model.PlayerPropertyProtos.PlayerProperty.getDefaultInstance();
          onChanged();
        } else {
          propertyBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      /**
       * <code>optional .com.origingame.model.PlayerProperty property = 2;</code>
       */
      public com.origingame.model.PlayerPropertyProtos.PlayerProperty.Builder getPropertyBuilder() {
        bitField0_ |= 0x00000002;
        onChanged();
        return getPropertyFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .com.origingame.model.PlayerProperty property = 2;</code>
       */
      public com.origingame.model.PlayerPropertyProtos.PlayerPropertyOrBuilder getPropertyOrBuilder() {
        if (propertyBuilder_ != null) {
          return propertyBuilder_.getMessageOrBuilder();
        } else {
          return property_;
        }
      }
      /**
       * <code>optional .com.origingame.model.PlayerProperty property = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          com.origingame.model.PlayerPropertyProtos.PlayerProperty, com.origingame.model.PlayerPropertyProtos.PlayerProperty.Builder, com.origingame.model.PlayerPropertyProtos.PlayerPropertyOrBuilder> 
          getPropertyFieldBuilder() {
        if (propertyBuilder_ == null) {
          propertyBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.origingame.model.PlayerPropertyProtos.PlayerProperty, com.origingame.model.PlayerPropertyProtos.PlayerProperty.Builder, com.origingame.model.PlayerPropertyProtos.PlayerPropertyOrBuilder>(
                  getProperty(),
                  getParentForChildren(),
                  isClean());
          property_ = null;
        }
        return propertyBuilder_;
      }

      private java.util.List<com.origingame.model.PlayerItemProtos.PlayerItem> items_ =
        java.util.Collections.emptyList();
      private void ensureItemsIsMutable() {
        if (!((bitField0_ & 0x00000004) == 0x00000004)) {
          items_ = new java.util.ArrayList<com.origingame.model.PlayerItemProtos.PlayerItem>(items_);
          bitField0_ |= 0x00000004;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          com.origingame.model.PlayerItemProtos.PlayerItem, com.origingame.model.PlayerItemProtos.PlayerItem.Builder, com.origingame.model.PlayerItemProtos.PlayerItemOrBuilder> itemsBuilder_;

      /**
       * <code>repeated .com.origingame.model.PlayerItem items = 21;</code>
       */
      public java.util.List<com.origingame.model.PlayerItemProtos.PlayerItem> getItemsList() {
        if (itemsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(items_);
        } else {
          return itemsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .com.origingame.model.PlayerItem items = 21;</code>
       */
      public int getItemsCount() {
        if (itemsBuilder_ == null) {
          return items_.size();
        } else {
          return itemsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .com.origingame.model.PlayerItem items = 21;</code>
       */
      public com.origingame.model.PlayerItemProtos.PlayerItem getItems(int index) {
        if (itemsBuilder_ == null) {
          return items_.get(index);
        } else {
          return itemsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .com.origingame.model.PlayerItem items = 21;</code>
       */
      public Builder setItems(
          int index, com.origingame.model.PlayerItemProtos.PlayerItem value) {
        if (itemsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureItemsIsMutable();
          items_.set(index, value);
          onChanged();
        } else {
          itemsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .com.origingame.model.PlayerItem items = 21;</code>
       */
      public Builder setItems(
          int index, com.origingame.model.PlayerItemProtos.PlayerItem.Builder builderForValue) {
        if (itemsBuilder_ == null) {
          ensureItemsIsMutable();
          items_.set(index, builderForValue.build());
          onChanged();
        } else {
          itemsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.origingame.model.PlayerItem items = 21;</code>
       */
      public Builder addItems(com.origingame.model.PlayerItemProtos.PlayerItem value) {
        if (itemsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureItemsIsMutable();
          items_.add(value);
          onChanged();
        } else {
          itemsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .com.origingame.model.PlayerItem items = 21;</code>
       */
      public Builder addItems(
          int index, com.origingame.model.PlayerItemProtos.PlayerItem value) {
        if (itemsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureItemsIsMutable();
          items_.add(index, value);
          onChanged();
        } else {
          itemsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .com.origingame.model.PlayerItem items = 21;</code>
       */
      public Builder addItems(
          com.origingame.model.PlayerItemProtos.PlayerItem.Builder builderForValue) {
        if (itemsBuilder_ == null) {
          ensureItemsIsMutable();
          items_.add(builderForValue.build());
          onChanged();
        } else {
          itemsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.origingame.model.PlayerItem items = 21;</code>
       */
      public Builder addItems(
          int index, com.origingame.model.PlayerItemProtos.PlayerItem.Builder builderForValue) {
        if (itemsBuilder_ == null) {
          ensureItemsIsMutable();
          items_.add(index, builderForValue.build());
          onChanged();
        } else {
          itemsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.origingame.model.PlayerItem items = 21;</code>
       */
      public Builder addAllItems(
          java.lang.Iterable<? extends com.origingame.model.PlayerItemProtos.PlayerItem> values) {
        if (itemsBuilder_ == null) {
          ensureItemsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, items_);
          onChanged();
        } else {
          itemsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .com.origingame.model.PlayerItem items = 21;</code>
       */
      public Builder clearItems() {
        if (itemsBuilder_ == null) {
          items_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
          onChanged();
        } else {
          itemsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .com.origingame.model.PlayerItem items = 21;</code>
       */
      public Builder removeItems(int index) {
        if (itemsBuilder_ == null) {
          ensureItemsIsMutable();
          items_.remove(index);
          onChanged();
        } else {
          itemsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .com.origingame.model.PlayerItem items = 21;</code>
       */
      public com.origingame.model.PlayerItemProtos.PlayerItem.Builder getItemsBuilder(
          int index) {
        return getItemsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .com.origingame.model.PlayerItem items = 21;</code>
       */
      public com.origingame.model.PlayerItemProtos.PlayerItemOrBuilder getItemsOrBuilder(
          int index) {
        if (itemsBuilder_ == null) {
          return items_.get(index);  } else {
          return itemsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .com.origingame.model.PlayerItem items = 21;</code>
       */
      public java.util.List<? extends com.origingame.model.PlayerItemProtos.PlayerItemOrBuilder> 
           getItemsOrBuilderList() {
        if (itemsBuilder_ != null) {
          return itemsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(items_);
        }
      }
      /**
       * <code>repeated .com.origingame.model.PlayerItem items = 21;</code>
       */
      public com.origingame.model.PlayerItemProtos.PlayerItem.Builder addItemsBuilder() {
        return getItemsFieldBuilder().addBuilder(
            com.origingame.model.PlayerItemProtos.PlayerItem.getDefaultInstance());
      }
      /**
       * <code>repeated .com.origingame.model.PlayerItem items = 21;</code>
       */
      public com.origingame.model.PlayerItemProtos.PlayerItem.Builder addItemsBuilder(
          int index) {
        return getItemsFieldBuilder().addBuilder(
            index, com.origingame.model.PlayerItemProtos.PlayerItem.getDefaultInstance());
      }
      /**
       * <code>repeated .com.origingame.model.PlayerItem items = 21;</code>
       */
      public java.util.List<com.origingame.model.PlayerItemProtos.PlayerItem.Builder> 
           getItemsBuilderList() {
        return getItemsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          com.origingame.model.PlayerItemProtos.PlayerItem, com.origingame.model.PlayerItemProtos.PlayerItem.Builder, com.origingame.model.PlayerItemProtos.PlayerItemOrBuilder> 
          getItemsFieldBuilder() {
        if (itemsBuilder_ == null) {
          itemsBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              com.origingame.model.PlayerItemProtos.PlayerItem, com.origingame.model.PlayerItemProtos.PlayerItem.Builder, com.origingame.model.PlayerItemProtos.PlayerItemOrBuilder>(
                  items_,
                  ((bitField0_ & 0x00000004) == 0x00000004),
                  getParentForChildren(),
                  isClean());
          items_ = null;
        }
        return itemsBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:com.origingame.model.PlayerModel)
    }

    static {
      defaultInstance = new PlayerModel(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.origingame.model.PlayerModel)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_origingame_model_PlayerModel_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_origingame_model_PlayerModel_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\030model/player_model.proto\022\024com.originga" +
      "me.model\032\033model/player_property.proto\032\027m" +
      "odel/player_item.proto\"\202\001\n\013PlayerModel\022\n" +
      "\n\002id\030\001 \001(\005\0226\n\010property\030\002 \001(\0132$.com.origi" +
      "ngame.model.PlayerProperty\022/\n\005items\030\025 \003(" +
      "\0132 .com.origingame.model.PlayerItemB\023B\021P" +
      "layerModelProtos"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.origingame.model.PlayerPropertyProtos.getDescriptor(),
          com.origingame.model.PlayerItemProtos.getDescriptor(),
        }, assigner);
    internal_static_com_origingame_model_PlayerModel_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_origingame_model_PlayerModel_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_origingame_model_PlayerModel_descriptor,
        new java.lang.String[] { "Id", "Property", "Items", });
    com.origingame.model.PlayerPropertyProtos.getDescriptor();
    com.origingame.model.PlayerItemProtos.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
