// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: model/player_property.proto

package com.origingame.model;

public final class PlayerPropertyProtos {
  private PlayerPropertyProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface PlayerPropertyOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.origingame.model.PlayerProperty)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional int32 id = 1;</code>
     */
    boolean hasId();
    /**
     * <code>optional int32 id = 1;</code>
     */
    int getId();

    /**
     * <code>optional string username = 2;</code>
     */
    boolean hasUsername();
    /**
     * <code>optional string username = 2;</code>
     */
    java.lang.String getUsername();
    /**
     * <code>optional string username = 2;</code>
     */
    com.google.protobuf.ByteString
        getUsernameBytes();

    /**
     * <code>optional string nickname = 3;</code>
     */
    boolean hasNickname();
    /**
     * <code>optional string nickname = 3;</code>
     */
    java.lang.String getNickname();
    /**
     * <code>optional string nickname = 3;</code>
     */
    com.google.protobuf.ByteString
        getNicknameBytes();

    /**
     * <code>optional int32 level = 4;</code>
     */
    boolean hasLevel();
    /**
     * <code>optional int32 level = 4;</code>
     */
    int getLevel();

    /**
     * <code>optional int32 vit = 5;</code>
     */
    boolean hasVit();
    /**
     * <code>optional int32 vit = 5;</code>
     */
    int getVit();

    /**
     * <code>optional int32 max_vit = 6;</code>
     */
    boolean hasMaxVit();
    /**
     * <code>optional int32 max_vit = 6;</code>
     */
    int getMaxVit();

    /**
     * <code>optional int32 gold = 7;</code>
     */
    boolean hasGold();
    /**
     * <code>optional int32 gold = 7;</code>
     */
    int getGold();

    /**
     * <code>optional int32 gem = 8;</code>
     */
    boolean hasGem();
    /**
     * <code>optional int32 gem = 8;</code>
     */
    int getGem();

    /**
     * <code>optional string outer_id = 9;</code>
     */
    boolean hasOuterId();
    /**
     * <code>optional string outer_id = 9;</code>
     */
    java.lang.String getOuterId();
    /**
     * <code>optional string outer_id = 9;</code>
     */
    com.google.protobuf.ByteString
        getOuterIdBytes();

    /**
     * <code>optional string password = 10;</code>
     */
    boolean hasPassword();
    /**
     * <code>optional string password = 10;</code>
     */
    java.lang.String getPassword();
    /**
     * <code>optional string password = 10;</code>
     */
    com.google.protobuf.ByteString
        getPasswordBytes();

    /**
     * <code>optional int32 session_id = 11;</code>
     */
    boolean hasSessionId();
    /**
     * <code>optional int32 session_id = 11;</code>
     */
    int getSessionId();

    /**
     * <code>optional int64 last_login_time = 12;</code>
     */
    boolean hasLastLoginTime();
    /**
     * <code>optional int64 last_login_time = 12;</code>
     */
    long getLastLoginTime();
  }
  /**
   * Protobuf type {@code com.origingame.model.PlayerProperty}
   */
  public static final class PlayerProperty extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:com.origingame.model.PlayerProperty)
      PlayerPropertyOrBuilder {
    // Use PlayerProperty.newBuilder() to construct.
    private PlayerProperty(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private PlayerProperty(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final PlayerProperty defaultInstance;
    public static PlayerProperty getDefaultInstance() {
      return defaultInstance;
    }

    public PlayerProperty getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private PlayerProperty(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              id_ = input.readInt32();
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              username_ = bs;
              break;
            }
            case 26: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000004;
              nickname_ = bs;
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              level_ = input.readInt32();
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              vit_ = input.readInt32();
              break;
            }
            case 48: {
              bitField0_ |= 0x00000020;
              maxVit_ = input.readInt32();
              break;
            }
            case 56: {
              bitField0_ |= 0x00000040;
              gold_ = input.readInt32();
              break;
            }
            case 64: {
              bitField0_ |= 0x00000080;
              gem_ = input.readInt32();
              break;
            }
            case 74: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000100;
              outerId_ = bs;
              break;
            }
            case 82: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000200;
              password_ = bs;
              break;
            }
            case 88: {
              bitField0_ |= 0x00000400;
              sessionId_ = input.readInt32();
              break;
            }
            case 96: {
              bitField0_ |= 0x00000800;
              lastLoginTime_ = input.readInt64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.origingame.model.PlayerPropertyProtos.internal_static_com_origingame_model_PlayerProperty_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.origingame.model.PlayerPropertyProtos.internal_static_com_origingame_model_PlayerProperty_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.origingame.model.PlayerPropertyProtos.PlayerProperty.class, com.origingame.model.PlayerPropertyProtos.PlayerProperty.Builder.class);
    }

    public static com.google.protobuf.Parser<PlayerProperty> PARSER =
        new com.google.protobuf.AbstractParser<PlayerProperty>() {
      public PlayerProperty parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new PlayerProperty(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<PlayerProperty> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int ID_FIELD_NUMBER = 1;
    private int id_;
    /**
     * <code>optional int32 id = 1;</code>
     */
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional int32 id = 1;</code>
     */
    public int getId() {
      return id_;
    }

    public static final int USERNAME_FIELD_NUMBER = 2;
    private java.lang.Object username_;
    /**
     * <code>optional string username = 2;</code>
     */
    public boolean hasUsername() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string username = 2;</code>
     */
    public java.lang.String getUsername() {
      java.lang.Object ref = username_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          username_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string username = 2;</code>
     */
    public com.google.protobuf.ByteString
        getUsernameBytes() {
      java.lang.Object ref = username_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        username_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int NICKNAME_FIELD_NUMBER = 3;
    private java.lang.Object nickname_;
    /**
     * <code>optional string nickname = 3;</code>
     */
    public boolean hasNickname() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional string nickname = 3;</code>
     */
    public java.lang.String getNickname() {
      java.lang.Object ref = nickname_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          nickname_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string nickname = 3;</code>
     */
    public com.google.protobuf.ByteString
        getNicknameBytes() {
      java.lang.Object ref = nickname_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        nickname_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int LEVEL_FIELD_NUMBER = 4;
    private int level_;
    /**
     * <code>optional int32 level = 4;</code>
     */
    public boolean hasLevel() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional int32 level = 4;</code>
     */
    public int getLevel() {
      return level_;
    }

    public static final int VIT_FIELD_NUMBER = 5;
    private int vit_;
    /**
     * <code>optional int32 vit = 5;</code>
     */
    public boolean hasVit() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional int32 vit = 5;</code>
     */
    public int getVit() {
      return vit_;
    }

    public static final int MAX_VIT_FIELD_NUMBER = 6;
    private int maxVit_;
    /**
     * <code>optional int32 max_vit = 6;</code>
     */
    public boolean hasMaxVit() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>optional int32 max_vit = 6;</code>
     */
    public int getMaxVit() {
      return maxVit_;
    }

    public static final int GOLD_FIELD_NUMBER = 7;
    private int gold_;
    /**
     * <code>optional int32 gold = 7;</code>
     */
    public boolean hasGold() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    /**
     * <code>optional int32 gold = 7;</code>
     */
    public int getGold() {
      return gold_;
    }

    public static final int GEM_FIELD_NUMBER = 8;
    private int gem_;
    /**
     * <code>optional int32 gem = 8;</code>
     */
    public boolean hasGem() {
      return ((bitField0_ & 0x00000080) == 0x00000080);
    }
    /**
     * <code>optional int32 gem = 8;</code>
     */
    public int getGem() {
      return gem_;
    }

    public static final int OUTER_ID_FIELD_NUMBER = 9;
    private java.lang.Object outerId_;
    /**
     * <code>optional string outer_id = 9;</code>
     */
    public boolean hasOuterId() {
      return ((bitField0_ & 0x00000100) == 0x00000100);
    }
    /**
     * <code>optional string outer_id = 9;</code>
     */
    public java.lang.String getOuterId() {
      java.lang.Object ref = outerId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          outerId_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string outer_id = 9;</code>
     */
    public com.google.protobuf.ByteString
        getOuterIdBytes() {
      java.lang.Object ref = outerId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        outerId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PASSWORD_FIELD_NUMBER = 10;
    private java.lang.Object password_;
    /**
     * <code>optional string password = 10;</code>
     */
    public boolean hasPassword() {
      return ((bitField0_ & 0x00000200) == 0x00000200);
    }
    /**
     * <code>optional string password = 10;</code>
     */
    public java.lang.String getPassword() {
      java.lang.Object ref = password_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          password_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string password = 10;</code>
     */
    public com.google.protobuf.ByteString
        getPasswordBytes() {
      java.lang.Object ref = password_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        password_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SESSION_ID_FIELD_NUMBER = 11;
    private int sessionId_;
    /**
     * <code>optional int32 session_id = 11;</code>
     */
    public boolean hasSessionId() {
      return ((bitField0_ & 0x00000400) == 0x00000400);
    }
    /**
     * <code>optional int32 session_id = 11;</code>
     */
    public int getSessionId() {
      return sessionId_;
    }

    public static final int LAST_LOGIN_TIME_FIELD_NUMBER = 12;
    private long lastLoginTime_;
    /**
     * <code>optional int64 last_login_time = 12;</code>
     */
    public boolean hasLastLoginTime() {
      return ((bitField0_ & 0x00000800) == 0x00000800);
    }
    /**
     * <code>optional int64 last_login_time = 12;</code>
     */
    public long getLastLoginTime() {
      return lastLoginTime_;
    }

    private void initFields() {
      id_ = 0;
      username_ = "";
      nickname_ = "";
      level_ = 0;
      vit_ = 0;
      maxVit_ = 0;
      gold_ = 0;
      gem_ = 0;
      outerId_ = "";
      password_ = "";
      sessionId_ = 0;
      lastLoginTime_ = 0L;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getUsernameBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getNicknameBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt32(4, level_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeInt32(5, vit_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeInt32(6, maxVit_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeInt32(7, gold_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        output.writeInt32(8, gem_);
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        output.writeBytes(9, getOuterIdBytes());
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        output.writeBytes(10, getPasswordBytes());
      }
      if (((bitField0_ & 0x00000400) == 0x00000400)) {
        output.writeInt32(11, sessionId_);
      }
      if (((bitField0_ & 0x00000800) == 0x00000800)) {
        output.writeInt64(12, lastLoginTime_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getUsernameBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getNicknameBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, level_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, vit_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(6, maxVit_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(7, gold_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(8, gem_);
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(9, getOuterIdBytes());
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(10, getPasswordBytes());
      }
      if (((bitField0_ & 0x00000400) == 0x00000400)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(11, sessionId_);
      }
      if (((bitField0_ & 0x00000800) == 0x00000800)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(12, lastLoginTime_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.origingame.model.PlayerPropertyProtos.PlayerProperty parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.origingame.model.PlayerPropertyProtos.PlayerProperty parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.origingame.model.PlayerPropertyProtos.PlayerProperty parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.origingame.model.PlayerPropertyProtos.PlayerProperty parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.origingame.model.PlayerPropertyProtos.PlayerProperty parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.origingame.model.PlayerPropertyProtos.PlayerProperty parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.origingame.model.PlayerPropertyProtos.PlayerProperty parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.origingame.model.PlayerPropertyProtos.PlayerProperty parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.origingame.model.PlayerPropertyProtos.PlayerProperty parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.origingame.model.PlayerPropertyProtos.PlayerProperty parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.origingame.model.PlayerPropertyProtos.PlayerProperty prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.origingame.model.PlayerProperty}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.origingame.model.PlayerProperty)
        com.origingame.model.PlayerPropertyProtos.PlayerPropertyOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.origingame.model.PlayerPropertyProtos.internal_static_com_origingame_model_PlayerProperty_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.origingame.model.PlayerPropertyProtos.internal_static_com_origingame_model_PlayerProperty_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.origingame.model.PlayerPropertyProtos.PlayerProperty.class, com.origingame.model.PlayerPropertyProtos.PlayerProperty.Builder.class);
      }

      // Construct using com.origingame.model.PlayerPropertyProtos.PlayerProperty.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        id_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        username_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        nickname_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        level_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        vit_ = 0;
        bitField0_ = (bitField0_ & ~0x00000010);
        maxVit_ = 0;
        bitField0_ = (bitField0_ & ~0x00000020);
        gold_ = 0;
        bitField0_ = (bitField0_ & ~0x00000040);
        gem_ = 0;
        bitField0_ = (bitField0_ & ~0x00000080);
        outerId_ = "";
        bitField0_ = (bitField0_ & ~0x00000100);
        password_ = "";
        bitField0_ = (bitField0_ & ~0x00000200);
        sessionId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000400);
        lastLoginTime_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000800);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.origingame.model.PlayerPropertyProtos.internal_static_com_origingame_model_PlayerProperty_descriptor;
      }

      public com.origingame.model.PlayerPropertyProtos.PlayerProperty getDefaultInstanceForType() {
        return com.origingame.model.PlayerPropertyProtos.PlayerProperty.getDefaultInstance();
      }

      public com.origingame.model.PlayerPropertyProtos.PlayerProperty build() {
        com.origingame.model.PlayerPropertyProtos.PlayerProperty result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.origingame.model.PlayerPropertyProtos.PlayerProperty buildPartial() {
        com.origingame.model.PlayerPropertyProtos.PlayerProperty result = new com.origingame.model.PlayerPropertyProtos.PlayerProperty(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.id_ = id_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.username_ = username_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.nickname_ = nickname_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.level_ = level_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.vit_ = vit_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.maxVit_ = maxVit_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.gold_ = gold_;
        if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
          to_bitField0_ |= 0x00000080;
        }
        result.gem_ = gem_;
        if (((from_bitField0_ & 0x00000100) == 0x00000100)) {
          to_bitField0_ |= 0x00000100;
        }
        result.outerId_ = outerId_;
        if (((from_bitField0_ & 0x00000200) == 0x00000200)) {
          to_bitField0_ |= 0x00000200;
        }
        result.password_ = password_;
        if (((from_bitField0_ & 0x00000400) == 0x00000400)) {
          to_bitField0_ |= 0x00000400;
        }
        result.sessionId_ = sessionId_;
        if (((from_bitField0_ & 0x00000800) == 0x00000800)) {
          to_bitField0_ |= 0x00000800;
        }
        result.lastLoginTime_ = lastLoginTime_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.origingame.model.PlayerPropertyProtos.PlayerProperty) {
          return mergeFrom((com.origingame.model.PlayerPropertyProtos.PlayerProperty)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.origingame.model.PlayerPropertyProtos.PlayerProperty other) {
        if (other == com.origingame.model.PlayerPropertyProtos.PlayerProperty.getDefaultInstance()) return this;
        if (other.hasId()) {
          setId(other.getId());
        }
        if (other.hasUsername()) {
          bitField0_ |= 0x00000002;
          username_ = other.username_;
          onChanged();
        }
        if (other.hasNickname()) {
          bitField0_ |= 0x00000004;
          nickname_ = other.nickname_;
          onChanged();
        }
        if (other.hasLevel()) {
          setLevel(other.getLevel());
        }
        if (other.hasVit()) {
          setVit(other.getVit());
        }
        if (other.hasMaxVit()) {
          setMaxVit(other.getMaxVit());
        }
        if (other.hasGold()) {
          setGold(other.getGold());
        }
        if (other.hasGem()) {
          setGem(other.getGem());
        }
        if (other.hasOuterId()) {
          bitField0_ |= 0x00000100;
          outerId_ = other.outerId_;
          onChanged();
        }
        if (other.hasPassword()) {
          bitField0_ |= 0x00000200;
          password_ = other.password_;
          onChanged();
        }
        if (other.hasSessionId()) {
          setSessionId(other.getSessionId());
        }
        if (other.hasLastLoginTime()) {
          setLastLoginTime(other.getLastLoginTime());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.origingame.model.PlayerPropertyProtos.PlayerProperty parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.origingame.model.PlayerPropertyProtos.PlayerProperty) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int id_ ;
      /**
       * <code>optional int32 id = 1;</code>
       */
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional int32 id = 1;</code>
       */
      public int getId() {
        return id_;
      }
      /**
       * <code>optional int32 id = 1;</code>
       */
      public Builder setId(int value) {
        bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 id = 1;</code>
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object username_ = "";
      /**
       * <code>optional string username = 2;</code>
       */
      public boolean hasUsername() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string username = 2;</code>
       */
      public java.lang.String getUsername() {
        java.lang.Object ref = username_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            username_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string username = 2;</code>
       */
      public com.google.protobuf.ByteString
          getUsernameBytes() {
        java.lang.Object ref = username_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          username_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string username = 2;</code>
       */
      public Builder setUsername(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        username_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string username = 2;</code>
       */
      public Builder clearUsername() {
        bitField0_ = (bitField0_ & ~0x00000002);
        username_ = getDefaultInstance().getUsername();
        onChanged();
        return this;
      }
      /**
       * <code>optional string username = 2;</code>
       */
      public Builder setUsernameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        username_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object nickname_ = "";
      /**
       * <code>optional string nickname = 3;</code>
       */
      public boolean hasNickname() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional string nickname = 3;</code>
       */
      public java.lang.String getNickname() {
        java.lang.Object ref = nickname_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            nickname_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string nickname = 3;</code>
       */
      public com.google.protobuf.ByteString
          getNicknameBytes() {
        java.lang.Object ref = nickname_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          nickname_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string nickname = 3;</code>
       */
      public Builder setNickname(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        nickname_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string nickname = 3;</code>
       */
      public Builder clearNickname() {
        bitField0_ = (bitField0_ & ~0x00000004);
        nickname_ = getDefaultInstance().getNickname();
        onChanged();
        return this;
      }
      /**
       * <code>optional string nickname = 3;</code>
       */
      public Builder setNicknameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        nickname_ = value;
        onChanged();
        return this;
      }

      private int level_ ;
      /**
       * <code>optional int32 level = 4;</code>
       */
      public boolean hasLevel() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional int32 level = 4;</code>
       */
      public int getLevel() {
        return level_;
      }
      /**
       * <code>optional int32 level = 4;</code>
       */
      public Builder setLevel(int value) {
        bitField0_ |= 0x00000008;
        level_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 level = 4;</code>
       */
      public Builder clearLevel() {
        bitField0_ = (bitField0_ & ~0x00000008);
        level_ = 0;
        onChanged();
        return this;
      }

      private int vit_ ;
      /**
       * <code>optional int32 vit = 5;</code>
       */
      public boolean hasVit() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional int32 vit = 5;</code>
       */
      public int getVit() {
        return vit_;
      }
      /**
       * <code>optional int32 vit = 5;</code>
       */
      public Builder setVit(int value) {
        bitField0_ |= 0x00000010;
        vit_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 vit = 5;</code>
       */
      public Builder clearVit() {
        bitField0_ = (bitField0_ & ~0x00000010);
        vit_ = 0;
        onChanged();
        return this;
      }

      private int maxVit_ ;
      /**
       * <code>optional int32 max_vit = 6;</code>
       */
      public boolean hasMaxVit() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>optional int32 max_vit = 6;</code>
       */
      public int getMaxVit() {
        return maxVit_;
      }
      /**
       * <code>optional int32 max_vit = 6;</code>
       */
      public Builder setMaxVit(int value) {
        bitField0_ |= 0x00000020;
        maxVit_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 max_vit = 6;</code>
       */
      public Builder clearMaxVit() {
        bitField0_ = (bitField0_ & ~0x00000020);
        maxVit_ = 0;
        onChanged();
        return this;
      }

      private int gold_ ;
      /**
       * <code>optional int32 gold = 7;</code>
       */
      public boolean hasGold() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      /**
       * <code>optional int32 gold = 7;</code>
       */
      public int getGold() {
        return gold_;
      }
      /**
       * <code>optional int32 gold = 7;</code>
       */
      public Builder setGold(int value) {
        bitField0_ |= 0x00000040;
        gold_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 gold = 7;</code>
       */
      public Builder clearGold() {
        bitField0_ = (bitField0_ & ~0x00000040);
        gold_ = 0;
        onChanged();
        return this;
      }

      private int gem_ ;
      /**
       * <code>optional int32 gem = 8;</code>
       */
      public boolean hasGem() {
        return ((bitField0_ & 0x00000080) == 0x00000080);
      }
      /**
       * <code>optional int32 gem = 8;</code>
       */
      public int getGem() {
        return gem_;
      }
      /**
       * <code>optional int32 gem = 8;</code>
       */
      public Builder setGem(int value) {
        bitField0_ |= 0x00000080;
        gem_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 gem = 8;</code>
       */
      public Builder clearGem() {
        bitField0_ = (bitField0_ & ~0x00000080);
        gem_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object outerId_ = "";
      /**
       * <code>optional string outer_id = 9;</code>
       */
      public boolean hasOuterId() {
        return ((bitField0_ & 0x00000100) == 0x00000100);
      }
      /**
       * <code>optional string outer_id = 9;</code>
       */
      public java.lang.String getOuterId() {
        java.lang.Object ref = outerId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            outerId_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string outer_id = 9;</code>
       */
      public com.google.protobuf.ByteString
          getOuterIdBytes() {
        java.lang.Object ref = outerId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          outerId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string outer_id = 9;</code>
       */
      public Builder setOuterId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000100;
        outerId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string outer_id = 9;</code>
       */
      public Builder clearOuterId() {
        bitField0_ = (bitField0_ & ~0x00000100);
        outerId_ = getDefaultInstance().getOuterId();
        onChanged();
        return this;
      }
      /**
       * <code>optional string outer_id = 9;</code>
       */
      public Builder setOuterIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000100;
        outerId_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object password_ = "";
      /**
       * <code>optional string password = 10;</code>
       */
      public boolean hasPassword() {
        return ((bitField0_ & 0x00000200) == 0x00000200);
      }
      /**
       * <code>optional string password = 10;</code>
       */
      public java.lang.String getPassword() {
        java.lang.Object ref = password_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            password_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string password = 10;</code>
       */
      public com.google.protobuf.ByteString
          getPasswordBytes() {
        java.lang.Object ref = password_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          password_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string password = 10;</code>
       */
      public Builder setPassword(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000200;
        password_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string password = 10;</code>
       */
      public Builder clearPassword() {
        bitField0_ = (bitField0_ & ~0x00000200);
        password_ = getDefaultInstance().getPassword();
        onChanged();
        return this;
      }
      /**
       * <code>optional string password = 10;</code>
       */
      public Builder setPasswordBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000200;
        password_ = value;
        onChanged();
        return this;
      }

      private int sessionId_ ;
      /**
       * <code>optional int32 session_id = 11;</code>
       */
      public boolean hasSessionId() {
        return ((bitField0_ & 0x00000400) == 0x00000400);
      }
      /**
       * <code>optional int32 session_id = 11;</code>
       */
      public int getSessionId() {
        return sessionId_;
      }
      /**
       * <code>optional int32 session_id = 11;</code>
       */
      public Builder setSessionId(int value) {
        bitField0_ |= 0x00000400;
        sessionId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 session_id = 11;</code>
       */
      public Builder clearSessionId() {
        bitField0_ = (bitField0_ & ~0x00000400);
        sessionId_ = 0;
        onChanged();
        return this;
      }

      private long lastLoginTime_ ;
      /**
       * <code>optional int64 last_login_time = 12;</code>
       */
      public boolean hasLastLoginTime() {
        return ((bitField0_ & 0x00000800) == 0x00000800);
      }
      /**
       * <code>optional int64 last_login_time = 12;</code>
       */
      public long getLastLoginTime() {
        return lastLoginTime_;
      }
      /**
       * <code>optional int64 last_login_time = 12;</code>
       */
      public Builder setLastLoginTime(long value) {
        bitField0_ |= 0x00000800;
        lastLoginTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 last_login_time = 12;</code>
       */
      public Builder clearLastLoginTime() {
        bitField0_ = (bitField0_ & ~0x00000800);
        lastLoginTime_ = 0L;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.origingame.model.PlayerProperty)
    }

    static {
      defaultInstance = new PlayerProperty(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.origingame.model.PlayerProperty)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_origingame_model_PlayerProperty_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_origingame_model_PlayerProperty_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\033model/player_property.proto\022\024com.origi" +
      "ngame.model\"\331\001\n\016PlayerProperty\022\n\n\002id\030\001 \001" +
      "(\005\022\020\n\010username\030\002 \001(\t\022\020\n\010nickname\030\003 \001(\t\022\r" +
      "\n\005level\030\004 \001(\005\022\013\n\003vit\030\005 \001(\005\022\017\n\007max_vit\030\006 " +
      "\001(\005\022\014\n\004gold\030\007 \001(\005\022\013\n\003gem\030\010 \001(\005\022\020\n\010outer_" +
      "id\030\t \001(\t\022\020\n\010password\030\n \001(\t\022\022\n\nsession_id" +
      "\030\013 \001(\005\022\027\n\017last_login_time\030\014 \001(\003B\026B\024Playe" +
      "rPropertyProtos"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_origingame_model_PlayerProperty_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_origingame_model_PlayerProperty_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_origingame_model_PlayerProperty_descriptor,
        new java.lang.String[] { "Id", "Username", "Nickname", "Level", "Vit", "MaxVit", "Gold", "Gem", "OuterId", "Password", "SessionId", "LastLoginTime", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
